syntax on

set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set number
set hlsearch
set ruler
set ai
set autoindent
set backspace=2
set relativenumber
set splitbelow
set splitright
let $CXXFLAGS="-o -Wall -std=c++17"
nnoremap <F4> :make %<<CR>
nnoremap <F5> :!./%<<CR>
noremap <F9> :au BufNewFile *.cpp r ~/.vim/templates/skeleton.cpp<CR>

colorscheme peachpuff
highlight Visual cterm=bold ctermbg=Blue ctermfg=NONE
highlight Comment ctermfg=green
hi Search cterm=NONE ctermfg=Black ctermbg=Cyan


let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_bufsettings = 'noma nomod nu nobl nowrap ro'
